# Generated by Django 4.2.18 on 2025-06-07 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Desarrollador', 'verbose_name_plural': 'Desarrolladores'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Franquicia', 'verbose_name_plural': 'Franquicias'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AlterModelOptions(
            name='gamelist',
            options={'verbose_name': 'Lista de Juegos', 'verbose_name_plural': 'Listas de Juegos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Entrada de diario', 'verbose_name_plural': 'Entradas de diario'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Distribuidora', 'verbose_name_plural': 'Distribuidoras'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.game', verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación promedio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.developer', verbose_name='Desarrollador'),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Clasificación ESRB'),
        ),
        migrations.AlterField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.franchise', verbose_name='Franquicia'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='core.genre', verbose_name='Géneros'),
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer_support',
            field=models.BooleanField(default=False, verbose_name='Soporte multijugador'),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_ratings',
            field=models.IntegerField(default=0, verbose_name='Número de calificaciones'),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_reviews',
            field=models.IntegerField(default=0, verbose_name='Número de reseñas'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='core.platform', verbose_name='Plataformas'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.publisher', verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='core.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_played',
            field=models.IntegerField(default=0, verbose_name='Tiempo jugado (horas)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Añadido el'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='games',
            field=models.ManyToManyField(to='core.game', verbose_name='Juegos'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Es público'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='name',
            field=models.CharField(default='Unnamed List', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la entrada'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_text',
            field=models.TextField(verbose_name='Texto de la entrada'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token de autenticación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
