# Generated by Django 4.2.18 on 2025-06-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_achievement_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Calificación')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='Texto de la reseña')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='Completado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'unique_together': {('user', 'game')},
            },
        ),
    ]
