# Generated by Django 4.2.18 on 2025-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='name',
            field=models.CharField(choices=[('Jugando', 'Jugando'), ('Terminado', 'Terminado'), ('En espera', 'En espera'), ('Planificado para jugar', 'Planificado para jugar')], max_length=32, verbose_name='Nombre'),
        ),
    ]
