# Generated by Django 4.2 on 2025-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
