# Generated by Django 4.2 on 2025-04-01 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_achievement_developer_franchise_genre_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='friends_played',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='list',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='name',
            field=models.CharField(default='Unnamed List', max_length=255),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ListInfo',
        ),
    ]
